### PR TITLE
grammar: "runs within a workspace"

### PR DESCRIPTION
**Pull request by aslonnie**
rather than "is run within a workspace"

### CODE REVIEW

**Comment by aslonnie** [comment]
or maybe it should be "This tutorial is **a** run within a workspace" ? I feel that using run in verb form is more direct.

**Comment by scottsun94** [comment]
Will leave this to @emmyscode or @angelinalg

**Review by emmyscode — CHANGES_REQUESTED** [review]
@angelinalg Can we actually take this as an opportunity to remove the reference to an example running in a workspace, so that it doesn't read weirdly when it's just in docs?

**Comment by angelinalg** [comment]
Thanks for filing this! We'll add it to the backlog for sure.

**Comment by aslonnie** [comment]
> take this as an opportunity to remove the reference to an example running in a workspace, so that it doesn't read weirdly when it's just in docs?

any specific action item for this PR?

**Review by emmyscode — APPROVED** [review]
Let's just get this PR in for now. No blocker on this.

**Comment by angelinalg** [comment]
No action.

**Comment by aslonnie** [comment]
ok, let me merge this, and I will try to go through the template release steps.

**Pull request merged**
