### PR TITLE
Adding template for image classification service

### PR DESCRIPTION
**Pull request by akshay-anyscale**

### CODE REVIEW

**Comment by akshay-anyscale** [comment]
Screenshot 2023-07-07 at 7 51 19 PM
Tested on CI

**Comment by mjconnor** [comment]
why have a cluster_env yaml? its defined else where right? so could leave it blank and service rollout would still work

**Comment by akshay-anyscale** [comment]
It's using BYOD, I just added this so that people know how to build it if they need to add/remove stuff.

**Review by mjconnor — APPROVED** [review]

**Comment by akshay-anyscale** [comment]
updated the template with FastAPI UploadFile

**Review by edoakes — APPROVED** [review]

**Pull request merged**
