### PR TITLE
[Triton] drop gpu header dependency

### PR DESCRIPTION
**Pull request by GeneDer**
Wrap model compile and upload in a ray actor to run on the GPU worker so we can remove the GPU head node dependency on this template. Also fix the configs. 

Full walkthrough video: https://drive.google.com/file/d/1HGOFNYneniECHuP4iX43_IsjiW9zYZRj/view?usp=sharing

### CODE REVIEW

**Review by shomilj — COMMENTED** [review]
can you just delete configs/triton_services/aws.yaml and replace with default serverless_config

**Review by shomilj — COMMENTED** [review]
thanks for doing this!

**Comment by GeneDer** [comment]
> can you just delete configs/triton_services/aws.yaml and replace with default serverless_config

Good call, made the change in product repo to use the serverless configs https://github.com/anyscale/product/pull/29368/commits/82f181483492cf3f43fbd362a475805199fca65a

**Review by shomilj — APPROVED** [review]
sweet!

**Pull request merged**
