### PR TITLE
Update LoRA learning rates

### PR DESCRIPTION
**Pull request by ArturNiederfahrenhorst**
@SumanthRH flagged to me that our learning rates on the templates are lower. We have been having a too low learning rate on the templates all along.

Thanks @SumanthRH 

Some context on learning rates from instacart workload. TLDR: 1e-4 is a good number.

https://anyscaleteam.slack.com/archives/C035J1Z5EUB/p1711132679445679?thread_ts=1710815945.855269&cid=C035J1Z5EUB

### CODE REVIEW

**Comment by kouroshHakha** [comment]
@ArturNiederfahrenhorst while you are at it :) https://anyscale1.atlassian.net/browse/AE-547 This ticket basically tracked this issue + the lack of documentation of `max_padding`

**Comment by ArturNiederfahrenhorst** [comment]
@kouroshHakha Assuming you mean the line `padding: "max_length"` that we have in other configs: That line does not exist in the templates. It's "longest" by default. Please repeat the precise ask here for me

**Comment by kouroshHakha** [comment]
ok so what I meant is that to include `padding: "longest"` explicitly in all the yamls and then add a comment that says what the other options are, when they should be used. I want people to know that `padding: "max_length"` should be used when doing profiling to make sure they don't oom at the given context length.

**Review by kouroshHakha — APPROVED** [review]

**Comment by ArturNiederfahrenhorst** [comment]
I did a test run with this on one of the configs just to be sure, it's fine

**Pull request merged**
